# Generated by Django 4.1 on 2022-08-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_at_user_updated_at"),
        ("recipes", "0002_alter_recipe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="users.user",
            ),
        ),
    ]
